### ISSUE TITLE
Inconsistent reader:

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf#227] opened 2015-10-28 23:07 UTC
```ruby
RDF::Reader.for(content_type: 'text/turtle')
=> RDF::Raptor::Turtle::Reader	
RDF::Reader.for(:ttl)
=> RDF::Turtle::Reader
```

**Comment by gkellogg** [comment] 2015-10-28 23:41
If you include both Raptor and rdf-turtle, something's going to give. both define :`turtle`, but rdf-turtle also defines a `TTL` class, enabling the `:ttl` shortcut. Depending on the order of include `RDF::Reader.for(:turtle)` will give one or the other.

I don't think there's a bug here, but a `TTL` format class could be added to Raptor, if you think it's important. Note that other readers (e.g., RDFa) create similar convenience format classes, which may not be consistent when there are multiple formats/readers/writers defined.

**Comment by gkellogg** [comment] 2015-10-29 23:31
@jcoyne, what would you like to see done here? If you're satisfied with my answer, can you close it? Otherwise, suggest some remediation.

**Comment by no-reply** [comment] 2015-10-30 04:34
I'm +1 on opening an issue in RDF::Raptor for this. I would patch that along with my other WIP on that issue.

**Comment by jcoyne** [comment] 2015-10-30 12:04
I think that `RDF::Reader.for(:ttl)` should return `RDF::Raptor::Turtle::Reader` if raptor is available. That would be the least surprising thing to me.

**Comment by tpendragon** [comment] 2015-10-30 22:42
I think the issue is bigger - there needs to be a way to assert which format takes precedence for a given identifier at an application level. The reliance on `def inherited` and the `@@subclasses` class variable doesn't let us do that.

**Comment by no-reply** [comment] 2015-11-02 22:28
@tpendragon we discussed this on Friday; notes are at: http://irclog.whitequark.org/ruby-rdf/2015-10-30#14470641;

The agreement was that we would institute a last-loaded approach; in the following example, we would expect `:ttl` (etc...) to use `RDF::Raptor::Turtle`, but `:ntriples` to use `RDF::Ntriples`. 

```ruby
require 'rdf/turtle'
require 'rdf/raptor'
require 'rdf/ntriples'
```

There's a further agreement that officially supported `Format`s should strive for uniform symbol, content-type, and extension support.

Would that approach resolve the problem from your perspective?

**Comment by tpendragon** [comment] 2015-11-02 22:49
@no-reply Probably? Depending on load order could get interesting with Rails, but we'll see if it becomes an issue.

**Comment by gkellogg** [comment] 2015-11-03 23:22
I've made appropriate changes to various readers, and to base support in RDF::Format. @tpendragon, please see if this works okay for you and close the issue if so.

Note that, in specs, getting rid of RDF::NTriples is challenging, but that shouldn't be an issue in operational use.

**Comment by tpendragon** [comment] 2015-11-03 23:25
This is @jcoyne's issue, but that seems fine.

**Comment by jcoyne** [comment] 2015-11-03 23:28
I delegate my proxy to @tpendragon

**Comment by tpendragon** [comment] 2015-11-03 23:46
It looks like it works well enough. The readers I expect show up. @jcoyne close?

**Closed** 2015-11-04 14:43 UTC
Labels: 1.99.1
