### ISSUE TITLE
Is there a "prettier"

### ISSUE THREAD

**Issue by markwilkinson** [ruby-rdf/rdf#423] opened 2021-02-12 11:14 UTC
Hi Gregg!

No urgency on this because my code works, it's mostly a stylistic question:

```
    g = RDF::Graph.load("https://w3id.org/duchenne-proms")
    RDF::Vocabulary.from_graph(g, url: "https://w3id.org/duchenne-proms", class_name: "DDP")
    t = DDP.find_term("https://w3id.org/duchenne-proms#DDP_00064")
    pref = DDP.find("http://purl.org/dc/elements/1.1/").__prefix__
    t.properties[(pref.to_s + ":description").to_sym]
```

those last two lines are really ugly... I am sure there must be a better way to do it!?  Your APIs are usually more elegant than that :-)

Any suggestions welcome, but it's not urgent.  

Cheers!

**Comment by gkellogg** [comment] 2021-02-12 21:08
Closing as a duplicate of #424.

**Closed by gkellogg** 2021-02-12 21:08 UTC
